name: hoora
description: "A new Flutter project."
publish_to: 'none'

version: 1.13.0+38

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  shared_preferences: ^2.2.3
  firebase_core: ^2.27.2
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  firebase_crashlytics: ^3.5.0
  firebase_analytics: ^10.10.0
  firebase_storage: ^11.7.1
  cloud_functions: ^4.7.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  slider_button: ^2.1.0
  http: ^1.2.1
  google_fonts: ^6.2.1
  app_settings: ^5.1.1

    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1-9

flutter:
  uses-material-design: true
  fonts:
    - family: BalooPaaji
      fonts:
        - asset: assets/fonts/BalooPaaji2-Bold.ttf
        - asset: assets/fonts/BalooPaaji2-ExtraBold.ttf
        - asset: assets/fonts/BalooPaaji2-Medium.ttf
        - asset: assets/fonts/BalooPaaji2-Regular.ttf
        - asset: assets/fonts/BalooPaaji2-SemiBold.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: NunitoBlack
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
    - family: ARPDisplay
      fonts:
        - asset: assets/fonts/ARPDisplay-20.ttf
        - asset: assets/fonts/ARPDisplay-40.ttf
        - asset: assets/fonts/ARPDisplay-80.ttf
        - asset: assets/fonts/ARPDisplay-150.ttf
        - asset: assets/fonts/ARPDisplay-240.ttf
  assets:
      - assets/
      - assets/animations/
      - assets/svg/
      - assets/images/
      - assets/launcher_icon/

flutter_native_splash:
  ios: false
  android: true
  color: "#0E1626"
  image: "assets/images/android_splash.png"
  android_12:
    color: "#0E1626"
    image: "assets/images/android_splash.png"
